version: "3.9"
services:
  nginx:
    build: './nginx/'
    ports:
      - "80:80"
  image-upload:
    build: './node/'
    ports:
      - "3000:3000"
    environment:
      YOUR_GCP_PROJECT_ID: 
      YOUR_GCS_BUCKET_NAME: 
      YOUR_CLOUD_SQL_IP_ADDRESS: 
      YOUR_CLOUD_SQL_USER: 
      YOUR_CLOUD_SQL_PASSWORD: 
      YOUR_CLOUD_SQL_DATABASE: 
    volumes:
      - ./credentials.json:/app/keyfile.json
